### ISSUE TITLE
UEFI bios mode question

### ISSUE THREAD

**Issue by r9guy** [broozar/installDesktopFreeBSD#3]
Why script works only in non UEFI bios mode? 
I read at [https://x.org/releases/current/doc/man/man4/fbdev.4.xhtml](https://x.org/releases/current/doc/man/man4/fbdev.4.xhtml)
fbdev − video driver for framebuffer device is what system must be seeing then booted in UEFI mode. Can it be integrated into the script?

**Comment by htw-fcaf** [comment]
I originally created this script to automatically install a desktop environment as well as graphics drivers, especially nVidia, since I had a hard time doing it manually the first few times. In other words, I really wanted proper 3D acceleration. I don't know if this is possible with fbdev. In my experience, BIOS is necessary because the screen simply stays black with UEFI + Desktop + nvidia/radeon/intel drivers.

**Comment by r9guy** [comment]
You are right, I have also done my research. Apparently, FreeBSD is not yet mature then it comes to graphical subsystem. let's leave it to the time to fix it.
